# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "wifi-net"},
                   {ip: '192.168.111.1', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "routerC-router1"},
                   {ip: '192.168.222.1', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "routerC-router2"},
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.34', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.66', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "wifi-net"},
                ]
  },
  :office1Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.111.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "routerC-router1"},
                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
                   {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test-net"},
                   {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
                ]
  },

  :office1Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dev-net"},
                   {ip: '192.168.1.130', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "test-net"},
                   {ip: '192.168.1.194', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
                ]
  },
  :office2Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.222.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "routerC-router2"},
                   {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev-net"},
                   {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test-net"},
                   {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgmt-net"},
                   {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
                ]
  },

  :office2Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev-net"},
                   {ip: '192.168.2.66', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "test-net"},
                   {ip: '192.168.2.130', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                   {ip: '192.168.2.194', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            iptables -F 
#            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "192.168.0.0/22 via 192.168.255.2" >> /etc/sysconfig/network-scripts/route-eth1
            echo "192.168.111.0/30 via 192.168.255.2" >> /etc/sysconfig/network-scripts/route-eth1
            echo "192.168.222.0/30 via 192.168.255.2" >> /etc/sysconfig/network-scripts/route-eth1
            service network restart
            SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth2
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth3
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth4
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth5
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth6
            echo "192.168.1.0/24 via 192.168.111.2" >> /etc/sysconfig/network-scripts/route-eth5
            echo "192.168.2.0/24 via 192.168.222.2" >> /etc/sysconfig/network-scripts/route-eth6
            systemctl restart network
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth2
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth3
            echo "192.168.2.128/26 via 192.168.0.1" >> /etc/sysconfig/network-scripts/route-eth1
            echo "192.168.2.192/26 via 192.168.0.33" >> /etc/sysconfig/network-scripts/route-eth2
            echo "192.168.1.192/26 via 192.168.0.33" >> /etc/sysconfig/network-scripts/route-eth2
            systemctl restart network
            SHELL
        when "office1Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.111.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth2
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth3
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth4  
            systemctl restart network
            SHELL
        when "office1Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth2
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth3
            echo "192.168.2.0/26 via 192.168.1.1" >> /etc/sysconfig/network-scripts/route-eth1
            echo "192.168.2.64/26 via 192.168.1.129" >> /etc/sysconfig/network-scripts/route-eth2
            echo "192.168.2.192/26 via 192.168.1.193" >> /etc/sysconfig/network-scripts/route-eth3
            echo "192.168.0.32/28 via 192.168.1.193" >> /etc/sysconfig/network-scripts/route-eth3
            systemctl restart network
            SHELL
        when "office2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "net.ipv4.conf.all.forwarding=1" >> /etc/sysctl.conf
            sysctl -p /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.222.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth2
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth3
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth4
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth5
            systemctl restart network
            SHELL
        when "office2Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth2
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth3
            echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-eth4
            echo "192.168.0.0/28 via 192.168.2.129" >> /etc/sysconfig/network-scripts/route-eth3
            echo "192.168.1.0/25 via 192.168.2.1" >> /etc/sysconfig/network-scripts/route-eth1
            echo "192.168.1.128/26 via 192.168.2.65" >> /etc/sysconfig/network-scripts/route-eth2
            echo "192.168.1.192/26 via 192.168.2.193" >> /etc/sysconfig/network-scripts/route-eth4
            echo "192.168.0.32/28 via 192.168.2.193" >> /etc/sysconfig/network-scripts/route-eth4
            systemctl restart network
            SHELL

        end

      end

  end
  
  
end
