# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
#####################VM-Task2#########################################
  config.vm.define "task6" do |task6|
      task6.vm.network  "public_network", ip: "192.168.11.106"
      task6.vm.hostname = "task6"  
      task6.vm.provider "virtualbox" do |vb|
         vb.memory = "1024"
#         vb.customize ["createhd",  "--filename", "t6_dsk0", "--size", "10240"]
#         vb.customize ["createhd",  "--filename", "t6_dsk1", "--size", "4096"]
#         vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]
#         vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "1", "--type", "hdd", "--medium", "t6_dsk0.vdi"]
#         vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "2", "--type", "hdd", "--medium", "t6_dsk1.vdi"]
      end
  end
######################Provisioning####################################
  config.vm.provision "shell", inline: <<-SHELL
   yum update -y && yum clean all
   yum install -y epel-release
   yum install -y httpd
   yum install -y yum-utils 
   yum install -y rpm-build
   yum install -y rpmdevtools 
   yum install -y gcc
   yum install -y createrepo
   cd /root/
   rpmdev-setuptree
   yumdownloader --source nginx
   rpm -ihv nginx*.src.rpm
   yum-builddep nginx -y
   rpmbuild -ba rpmbuild/SPECS/nginx.spec
   cd /var/www/html
   createrepo .
   cp /root/rpmbuild/RPMS/x86_64/* .
   createrepo .
   systemctl start httpd
   mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.bak
  SHELL
end
